# Generated by Django 2.2.6 on 2019-10-24 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0002_auto_20191024_0850'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='type',
            field=models.CharField(choices=[('DV', 'developer'), ('PO', 'product owner')], default='DV', max_length=2),
        ),
    ]
