# Generated by Django 2.2.6 on 2019-10-22 03:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('productbacklog', '0002_remove_productbacklogitem_team'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productbacklogitem',
            old_name='sotrypoint',
            new_name='storypoint',
        ),
    ]
