# Generated by Django 2.2.6 on 2019-10-22 03:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('productbacklog', '0003_auto_20191022_0330'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productbacklogitem',
            old_name='project',
            new_name='product',
        ),
    ]
