# Generated by Django 2.2.6 on 2019-10-24 18:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('productbacklog', '0005_auto_20191024_1412'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductBacklogItemOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('head', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='headpbi', to='productbacklog.ProductBacklogItem')),
                ('productbacklogitem', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='productbacklog.ProductBacklogItem')),
                ('tail', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tailpbi', to='productbacklog.ProductBacklogItem')),
            ],
        ),
    ]
