# Generated by Django 2.2.6 on 2019-10-24 19:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('productbacklog', '0006_productbacklogitemorder'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productbacklogitemorder',
            old_name='head',
            new_name='headpbi',
        ),
        migrations.RenameField(
            model_name='productbacklogitemorder',
            old_name='tail',
            new_name='tailpbi',
        ),
    ]
