# Generated by Django 2.2.6 on 2019-10-25 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productbacklog', '0007_auto_20191024_1916'),
    ]

    operations = [
        migrations.AddField(
            model_name='productbacklogitem',
            name='oreder',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
