# Generated by Django 2.2.6 on 2019-10-25 04:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('productbacklog', '0008_productbacklogitem_oreder'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productbacklogitem',
            old_name='oreder',
            new_name='order',
        ),
    ]
