# Generated by Django 2.2.6 on 2019-10-25 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productbacklog', '0009_auto_20191025_0448'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productbacklogitem',
            name='order',
            field=models.IntegerField(default=0),
        ),
    ]
