# Generated by Django 2.2.6 on 2019-10-09 19:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('productbacklog', '0001_initial'),
        ('userprofile', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Sprint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField()),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('progress', models.CharField(max_length=10)),
                ('deadline', models.DateTimeField()),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='productbacklog.Product')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userprofile.Team')),
            ],
        ),
        migrations.CreateModel(
            name='SprintBacklogItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=200)),
                ('sprint', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sprintbacklog.Sprint')),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=200)),
                ('effort', models.IntegerField()),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('sprintbacklogitem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sprintbacklog.SprintBacklogItem')),
            ],
        ),
    ]
