# Generated by Django 2.2.6 on 2019-10-10 09:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('productbacklog', '0002_remove_productbacklogitem_team'),
        ('sprintbacklog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sprintbacklogitem',
            name='productbacklogitem',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='productbacklog.ProductBacklogItem'),
        ),
    ]
