# Generated by Django 2.2.6 on 2019-10-10 09:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sprintbacklog', '0002_sprintbacklogitem_productbacklogitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sprintbacklogitem',
            name='productbacklogitem',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='productbacklog.ProductBacklogItem'),
        ),
    ]
