# Generated by Django 2.2.6 on 2019-10-24 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sprintbacklog', '0004_auto_20191024_0523'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='name',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
