# Generated by Django 2.2.6 on 2019-10-24 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sprintbacklog', '0005_task_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sprint',
            name='progress',
            field=models.CharField(default='not start', max_length=10),
        ),
    ]
