# Generated by Django 2.2.6 on 2019-10-24 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sprintbacklog', '0006_auto_20191024_0931'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sprint',
            name='progress',
            field=models.CharField(choices=[('N', 'not start'), ('P', 'in progress'), ('C', 'complete')], default='N', max_length=1),
        ),
    ]
